<a href="https://colab.research.google.com/github/AlisonDelunaOrt/unidad1/blob/main/practica6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dalia Alison De luna Ortiz - 24/septiembre/2025
practica 6-Cortar arreglos NumPy
-----------------------------------------------
Slice en python tomar elementos de un indice determinado a otro determinado indice.Pasamos slice en lugar del indice de esta manera: [start:end]
si no pasamos el inicio se considera 0.
Si no pasamos al final,su longitud es considerada una matriz de una dimension.
------------------------------------------
EJEMPLO:([1,2,3,4,5,6,7])
cortar los elementos del indice 1 al indice 5
---------------------------


In [1]:
import numpy as np

arreglo= np.array([1,2,3,4,5,6,7])

print(arreglo[1:5])

[2 3 4 5]


EJEMPLO 2:
(1,2,3,4,5,6,7)
cortar del indice 4 hasta el fina de la matriz.
-----------------------------------------


In [2]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[4:])

[5 6 7]


EJEMPLO 3:
([1,2,3,4,5,6,7,])
cortar elementos desde el principio hasta el indice 5

In [6]:
import numpy as np
arreglo= np.array([1,2,3,4,5,6,7])
print(arreglo[0:5])

[1 2 3 4 5]


EJEMPLO 4:
([1,2,3,4,5,6,7])
corte negativo.Utilizamos el operador "menos" para hacer referencia a un indice desde el final.
---------------------------
Cortar de el indice 3 desde el final al indice 1 desde el final


In [7]:
import numpy as np
arreglo= np.array([1,2,3,4,5,6,7])
print(arreglo[-3:-1])

[5 6]
